modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="bloom_and_gloom"
version="0.2"
displayName="Bloom and Gloom"
authors="SchnappDragon, Edmord17"
description='''Plant mod that plans to add more flora to the overworld to make it feel lush. Currently adds rafflesias and kabloom bushes.'''