modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="bloom_and_gloom"
version="${file.jarVersion}"
displayName="Bloom and Gloom"
authors="SchnappDragon, Edmord17"
description='''Plant mod.
'''