modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SnappyDragon18/Bloom-and-Gloom/issues"

[[mods]]
  modId="bloom_and_gloom"
  version="0.2.2"
  displayName="Bloom and Gloom"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/bloom-and-gloom"
  logoFile="logo.png"
  authors="SchnappDragon, Edmord17"
  description='''Plant mod that plans to add more flora to the overworld to make it feel lush.'''


  [[dependencies.bloom_and_gloom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"